### ISSUE TITLE
download error on both album/track url `track = api.getTrack(int(track_id), track_quality)`

### ISSUE THREAD

**Issue by bachig26** [oskvr37/tiddl#2]
#### Album:
```
tiddl https://listen.tidal.com/album/315101913 -q master -p "E:\" -s
INFO TIDDL saved settings to .tiddl_config.json
download_path E:\
track_quality HI_RES_LOSSLESS
INFO TIDDL token expires in 6 days 23 hours
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Scripts\tiddl.exe\__main__.py", line 7, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiddl\__init__.py", line 131, in main
    track = api.getTrack(int(track_id), track_quality)
                         ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'https://listen.tidal.com/album/315101913'
```
#### Track:
```
tiddl https://listen.tidal.com/track/315101914 -q master -p "E:\" -s
INFO TIDDL saved settings to .tiddl_config.json
download_path E:\
track_quality HI_RES_LOSSLESS
INFO TIDDL token expires in 6 days 23 hours
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Scripts\tiddl.exe\__main__.py", line 7, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiddl\__init__.py", line 131, in main
    track = api.getTrack(int(track_id), track_quality)
                         ^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'https://listen.tidal.com/track/315101914'
```

**Comment by oskvr37** [comment]
Thank you for reporting this issue @bachig26.

Parsing `id` from Tidal URL is not implemented yet.
Currently you can't download albums as TIDDL only supports downloading tracks.
To download `https://listen.tidal.com/track/315101914` you would use `tiddl 315101914`.

We will be adding more functionalities and resolve your issue in the future versions!
