### ISSUE TITLE
error; can't run latest commit: 5ca8c07

### ISSUE THREAD

**Issue by bachig26** [oskvr37/tiddl#24]
i think it's showing the line 205 in init.py.
https://github.com/oskvr37/tiddl/blob/5ca8c07f1f0ce1d54b3f1174c00d544f4fde2941/tiddl/__init__.py#L205

```
tiddl
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Scripts\tiddl.exe\__main__.py", line 4, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiddl\__init__.py", line 205

    logger.info(f"album: {album["title"]}")
                                 ^^^^^
SyntaxError: f-string: unmatched '['
```

**Comment by oskvr37** [comment]
Should work now, I always forgot to change my python version from 3.12 to 3.10.
