### ISSUE TITLE
playlist download error

### ISSUE THREAD

**Issue by bachig26** [oskvr37/tiddl#26]
```
tiddl https://listen.tidal.com/playlist/744360b9-989e-4f7a-9a2d-bcc7c450ea15 -p "E:/eNT"
TIDDL playlist: Pop&B  (http://www.tidal.com/playlist/744360b9-989e-4f7a-9a2d-bcc7c450ea15)
TIDDL sleeping for 1.8s
TIDDL Pop&B /Check :: Max Quality - 24 bit 48.0 kHz
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Scripts\tiddl.exe\__main__.py", line 7, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiddl\__init__.py", line 273, in main
    downloadTrack(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiddl\__init__.py", line 196, in downloadTrack
    track_path = downloadTrackStream(
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiddl\download.py", line 217, in downloadTrackStream
    with open(file_name, "wb+") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'E:/eNT/Pop&B /Check.m4a'
```

**Comment by oskvr37** [comment]
Issue was with playlist that has space character in its title. Please check if it is working now.

Also I created `dev` branch with latest commits

**Comment by bachig26** [comment]
> Issue was with playlist that has space character in its title. Please check if it is working now.

it's fine now, it works well with dev branch.
