### ISSUE TITLE
Special Characters Download Error

### ISSUE THREAD

**Issue by bachig26** [oskvr37/tiddl#32]
```powershell
tiddl https://listen.tidal.com/playlist/f7cf4765-9955-493e-94d4-4a935646ac31 -p "E:\eNT"
[ TIDDL ] playlist: Grown Pop (http://www.tidal.com/playlist/f7cf4765-9955-493e-94d4-4a935646ac31)
[ TIDDL ] sleeping for 2.2s
[ TIDDL ] Warm Body :: Max Quality - 24 bit 44.1 kHz
threaded download ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 100%
[ TIDDL ] track saved as E:\eNT/Grown Pop/Warm Body.flac
[ TIDDL ] sleeping for 1.9s
[ TIDDL ] Sweet Caroline :: Max Quality - 24 bit 44.1 kHz
threaded download ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 100%
[ TIDDL ] track saved as E:\eNT/Grown Pop/Sweet Caroline.flac
[ TIDDL ] sleeping for 1.9s
[ TIDDL ] Under The Streetlight :: Max Quality - 24 bit 44.1 kHz
threaded download ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 100%
[ TIDDL ] track saved as E:\eNT/Grown Pop/Under The Streetlight.flac
[ TIDDL ] sleeping for 1.6s
[ TIDDL ] this feels good, huh? :: High Quality - 16 bit 44.1 kHz
Single URL ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ 100% 35.94 / 35.94 MB
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Scripts\tiddl.exe\__main__.py", line 7, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiddl\__init__.py", line 287, in main
    file_dir, file_name = downloadTrack(
                          ^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiddl\__init__.py", line 170, in downloadTrack
    track_path = downloadTrackStream(
                 ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\site-packages\tiddl\download.py", line 223, in downloadTrackStream
    with open(file_path, "wb+") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'E:\\eNT/Grown Pop/this feels good, huh?.flac'
```

**Comment by oskvr37** [comment]
I managed to download whole playlist without error, please try do the same with this latest fix

**Comment by bachig26** [comment]
> I managed to download whole playlist without error, please try do the same with this latest fix

it's fine now, thanks.
