### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by redlegoman** [oskvr37/tiddl#4]
I had version 1.1.0 working. I installed 1.2.0 from pip3 and now this happens:

> $ tiddl
> Traceback (most recent call last):
>   File "/home/andy/.local/bin/tiddl", line 5, in <module>
>     from tiddl import main
>   File "/home/andy/.local/lib/python3.10/site-packages/tiddl/__init__.py", line 6, in <module>
>     from .api import TidalApi
>   File "/home/andy/.local/lib/python3.10/site-packages/tiddl/api.py", line 4, in <module>
>     from .types import (
>   File "/home/andy/.local/lib/python3.10/site-packages/tiddl/types/__init__.py", line 3, in <module>
>     from .api import *
>   File "/home/andy/.local/lib/python3.10/site-packages/tiddl/types/api.py", line 3, in <module>
>     from .track import Track
>   File "/home/andy/.local/lib/python3.10/site-packages/tiddl/types/track.py", line 1, in <module>
>     from typing import TypedDict, Optional, List, Dict, Literal, NotRequired
> ImportError: cannot import name 'NotRequired' from 'typing' (/usr/lib/python3.10/typing.py)`

I tried upgrading the typing module tna

**Comment by oskvr37** [comment]
Thanks for reporting this issue.

NotRequired was introduced in python `3.11`, I'm developing TIDDL at latest `3.12.4`.
Please try upgrading your python version and see if it will be working.
Anyway I will modify the code to make it compatible with older python versions.

**Comment by redlegoman** [comment]
Ah ok. I am on Ubuntu 22.04 LTS and that's stuck at 3.10.

**Comment by redlegoman** [comment]
Ah, I managed to install python 3.11 and it looks good
